version: "3.9"  # optional since v1.27.0

services:

  node-app:
    build: ./node-app
    container_name: video-site-docker-node-app
    ports:
      - "4000:4000"
    links:
      - "mongo-db:mongo-db"

  mongo-db:
    build: 
      context: ./mongo-db
      args:
    container_name: video-site-docker-mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      mongo_db_user: ${mongo_db_user}
      mongo_db_pass: ${mongo_db_pass}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db/data:/data/db