version: "3.9"  # optional since v1.27.0

services:

  node-app:
    build: ./node-app
    ports:
      - "4000:4000"

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db-data:/data/db